<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Anchorline.FirstApp</RootNamespace>
    <AssemblyName>anchorline-first-app</AssemblyName>
    <EnableSdkContainerSupport>true</EnableSdkContainerSupport>
    <ContainerRepository>anchorline-first-app</ContainerRepository>
    <ContainerBaseImage>mcr.microsoft.com/dotnet/nightly/aspnet:10.0-noble-chiseled</ContainerBaseImage>
  </PropertyGroup>
</Project>
