"""FastAPI entry point for the Summitline Outfitters text + speech service.

Exposes six endpoints wired to the helpers students complete in Exercises 1-3:

- POST /analyze          — Exercise 1 (text.analyze)
- POST /extract          — Exercise 1 (text.extract)
- POST /translate        — Exercise 2 (translate.translate)
- POST /speak            — Exercise 3 (speech.synthesize)
- POST /transcribe       — Exercise 3 (speech.transcribe)
- POST /translate-speech — Exercise 3 (speech.translate_speech)

Students do NOT edit this file; it is the fixed harness for the exercise
``curl`` calls.
"""

from __future__ import annotations

import tempfile
import uuid
from pathlib import Path

from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.responses import FileResponse, JSONResponse

from app import speech, text, translate

app = FastAPI(
    title="Summitline Outfitters — Text & Speech",
    description=(
        "AI-103 Lesson 12 hands-on lab. Six endpoints wrap Azure AI Language, "
        "Azure OpenAI Responses API, Azure Translator, and Azure Speech SDK."
    ),
    version="1.0.0",
)


@app.get("/")
def root() -> dict:
    return {
        "service": "summitline-text-speech",
        "endpoints": [
            "POST /analyze",
            "POST /extract",
            "POST /translate",
            "POST /speak",
            "POST /transcribe",
            "POST /translate-speech",
        ],
    }


@app.post("/analyze")
def analyze_endpoint(content: str = Form(...)) -> JSONResponse:
    """Run Azure AI Language sentiment + key phrases."""
    try:
        return JSONResponse(text.analyze(content))
    except NotImplementedError as exc:
        raise HTTPException(status_code=501, detail=str(exc))


@app.post("/extract")
def extract_endpoint(content: str = Form(...)) -> JSONResponse:
    """Run Azure OpenAI Responses API structured JSON extraction."""
    try:
        return JSONResponse(text.extract(content))
    except NotImplementedError as exc:
        raise HTTPException(status_code=501, detail=str(exc))


@app.post("/translate")
def translate_endpoint(content: str = Form(...), to: str = Form(...)) -> JSONResponse:
    """Translate ``content`` into target language ``to`` (BCP-47 code)."""
    try:
        return JSONResponse({"text": translate.translate(content, to)})
    except NotImplementedError as exc:
        raise HTTPException(status_code=501, detail=str(exc))


@app.post("/speak")
def speak_endpoint(content: str = Form(...)) -> FileResponse:
    """Synthesize ``content`` to WAV and stream the file back."""
    out_path = Path(tempfile.gettempdir()) / f"speak-{uuid.uuid4().hex}.wav"
    try:
        speech.synthesize(content, out_path)
    except NotImplementedError as exc:
        raise HTTPException(status_code=501, detail=str(exc))
    return FileResponse(out_path, media_type="audio/wav", filename="speech.wav")


@app.post("/transcribe")
def transcribe_endpoint(audio: UploadFile = File(...)) -> JSONResponse:
    """Transcribe an uploaded WAV (16 kHz / 16-bit mono PCM)."""
    tmp = Path(tempfile.gettempdir()) / f"stt-{uuid.uuid4().hex}.wav"
    tmp.write_bytes(audio.file.read())
    try:
        return JSONResponse({"text": speech.transcribe(tmp)})
    except NotImplementedError as exc:
        raise HTTPException(status_code=501, detail=str(exc))
    finally:
        try:
            tmp.unlink()
        except OSError:
            pass


@app.post("/translate-speech")
def translate_speech_endpoint(
    audio: UploadFile = File(...),
    to: str = Form(...),
) -> JSONResponse:
    """Transcribe uploaded audio and translate into target language ``to``."""
    tmp = Path(tempfile.gettempdir()) / f"xlat-{uuid.uuid4().hex}.wav"
    tmp.write_bytes(audio.file.read())
    try:
        return JSONResponse(speech.translate_speech(tmp, to))
    except NotImplementedError as exc:
        raise HTTPException(status_code=501, detail=str(exc))
    finally:
        try:
            tmp.unlink()
        except OSError:
            pass
