<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Anchorline.Jobs</RootNamespace>
    <AssemblyName>anchorline-jobs</AssemblyName>
    <EnableSdkContainerSupport>true</EnableSdkContainerSupport>
    <ContainerRepository>anchorline-jobs</ContainerRepository>
    <ContainerBaseImage>mcr.microsoft.com/dotnet/nightly/runtime:10.0-noble-chiseled</ContainerBaseImage>
  </PropertyGroup>
</Project>
