apiVersion: v1
kind: Service
metadata:
  name: classifier
  namespace: northwind
  labels:
    app: classifier
spec:
  type: LoadBalancer
  selector:
    app: classifier
  ports:
    - name: http
      port: 80
      targetPort: 8000
